 version: '2'
 services:
   {{cookiecutter.project_name}}:
     build:
        context: .
        dockerfile: Dockerfile-dev
     volumes:
       - ./src:/usr/local/{{cookiecutter.project_name}}
     ports:
       - "8000:8000"

