FROM registry.manadrdev.com/ubuntu

MAINTAINER {{ cookiecutter.full_name }}
RUN	apt-get update && \
	apt-get install -y --allow-unauthenticated \
	curl \
	git \
	wget \
	python3 \
	python3-dev \
	python3-setuptools \
	libmysqlclient-dev \
	build-essential \
	libssl-dev \
	libffi-dev \
	ruby \
	mysql-client \
	default-jre-headless
RUN easy_install3 pip
RUN pip install --upgrade pip
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN gem install tiller
COPY tiller/ /etc/tiller
COPY apps.conf.example /etc/tiller/templates/apps.erb
RUN mkdir /var/local/{{cookiecutter.project_name}} /var/log/{{cookiecutter.project_name}} /var/local/requirements
WORKDIR /usr/local/{{cookiecutter.project_name}}
ADD requirements.txt /usr/local/requirements/requirements.txt
ADD pip_requirements /usr/local/requirements/pip_requirements
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH $PYTHONPATH:/usr/local/{{cookiecutter.project_name}}
ADD entrypoint.sh /tmp/entrypoint.sh
RUN chmod a+x /tmp/entrypoint.sh
CMD ["/usr/local/bin/tiller" , "-v"]
